services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  service1:
    build:
      context: ./service1
    ports:
      - "5001:5001"

  service3:
    build: ./service3
    ports:
      - "5003:5003"
      
  service4:
    build: ./service4
    ports:
      - "5004:5004"
      
  service6:
    build: ./service6
    ports:
      - "5006:5006"
      
  service9:
    build: ./service9
    ports:
      - "5009:5009"